#!/bin/bash
## Combine all the schema changes and dummy data in integer order
## and pass into the mysql client to create the database tables

BASEDIR=$(dirname $0)
COMBINED="$BASEDIR/all-schema-changes.sql"

## create the combined schema changes file
echo "" > $COMBINED

## concatenate the schema changes and dummy data into the single file
for INDEX in {1..50}; do
    if [ $INDEX -lt 10 ]
    then
        FILE="$BASEDIR/00"
    else
        FILE="$BASEDIR/0"
    fi
    SCHEMAFILE="$FILE$INDEX.sql"
    DUMMYFILE="$FILE$INDEX-dummy.sql"
    CLEANUPFILE="$FILE$INDEX-cleanup.sql"
    if [ -f $SCHEMAFILE ]
    then
        echo "Adding: $SCHEMAFILE"
        echo "START TRANSACTION;" >> $COMBINED
        cat $SCHEMAFILE >> $COMBINED
        echo "COMMIT;" >> $COMBINED
    fi
    if [ -f $DUMMYFILE ]
    then
        echo "Adding: $DUMMYFILE"
        echo "START TRANSACTION;" >> $COMBINED
        cat $DUMMYFILE >> $COMBINED
        echo "COMMIT;" >> $COMBINED
    fi
    if [ -f $CLEANUPFILE ]
    then
        echo "Adding: $CLEANUPFILE"
        echo "START TRANSACTION;" >> $COMBINED
        cat $CLEANUPFILE >> $COMBINED
        echo "COMMIT;" >> $COMBINED
    fi
done

if [ "$#" -lt 1 ]
then
    echo "Running: mysql < $COMBINED"
    mysql --verbose < $COMBINED
else
    echo "Running: mysql -u $1 -p < $COMBINED"
    mysql -u $1 -p --verbose < $COMBINED
fi

rm -f $COMBINED

