package uk.org.rbc1b.roms.db;
// Generated Apr 12, 2012 2:47:03 PM by Hibernate Tools 3.2.1.GA



/**
 * ProjectWorkStageId generated by hbm2java
 */
public class ProjectWorkStageId  implements java.io.Serializable {


     private String stageNumber;
     private String stageName;

    public ProjectWorkStageId() {
    }

    public ProjectWorkStageId(String stageNumber, String stageName) {
       this.stageNumber = stageNumber;
       this.stageName = stageName;
    }

    public String getStageNumber() {
        return this.stageNumber;
    }

    public void setStageNumber(String stageNumber) {
        this.stageNumber = stageNumber;
    }
    public String getStageName() {
        return this.stageName;
    }

    public void setStageName(String stageName) {
        this.stageName = stageName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProjectWorkStageId) ) return false;
		 ProjectWorkStageId castOther = ( ProjectWorkStageId ) other;

		 return ( (this.getStageNumber()==castOther.getStageNumber()) || ( this.getStageNumber()!=null && castOther.getStageNumber()!=null && this.getStageNumber().equals(castOther.getStageNumber()) ) )
 && ( (this.getStageName()==castOther.getStageName()) || ( this.getStageName()!=null && castOther.getStageName()!=null && this.getStageName().equals(castOther.getStageName()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getStageNumber() == null ? 0 : this.getStageNumber().hashCode() );
         result = 37 * result + ( getStageName() == null ? 0 : this.getStageName().hashCode() );
         return result;
   }


}


