package uk.org.rbc1b.roms.db;
// Generated Apr 12, 2012 2:36:09 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Congregation generated by hbm2java
 */
public class Congregation implements java.io.Serializable {

    private String congName;
    private KingdomHall kingdomHall;
    private Circuit circuit;
    private String congNumber;
    private String comments;
    private String rbcregion;
    private String publisher;
    private String attendance;
    private String khterritory;
    private String funds;
    private String stragegy;
    private String cpr;
    private Set<KingdomHall> kingdomHalls;

    public Congregation() {
    }

    public Congregation(String congName) {
        this.congName = congName;
    }

    public Congregation(String congName, KingdomHall kingdomHall, Circuit circuit, String congNumber, String comments, String rbcregion, String publisher, String attendance, String khterritory, String funds, String stragegy, String cpr, Set kingdomHalls) {
        this.congName = congName;
        this.kingdomHall = kingdomHall;
        this.circuit = circuit;
        this.congNumber = congNumber;
        this.comments = comments;
        this.rbcregion = rbcregion;
        this.publisher = publisher;
        this.attendance = attendance;
        this.khterritory = khterritory;
        this.funds = funds;
        this.stragegy = stragegy;
        this.cpr = cpr;
        this.kingdomHalls = kingdomHalls;
    }

    public String getCongName() {
        return this.congName;
    }

    public void setCongName(String congName) {
        this.congName = congName;
    }

    public KingdomHall getKingdomHall() {
        return this.kingdomHall;
    }

    public void setKingdomHall(KingdomHall kingdomHall) {
        this.kingdomHall = kingdomHall;
    }

    public Circuit getCircuit() {
        return this.circuit;
    }

    public void setCircuit(Circuit circuit) {
        this.circuit = circuit;
    }

    public String getCongNumber() {
        return this.congNumber;
    }

    public void setCongNumber(String congNumber) {
        this.congNumber = congNumber;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getRbcregion() {
        return this.rbcregion;
    }

    public void setRbcregion(String rbcregion) {
        this.rbcregion = rbcregion;
    }

    public String getPublisher() {
        return this.publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getAttendance() {
        return this.attendance;
    }

    public void setAttendance(String attendance) {
        this.attendance = attendance;
    }

    public String getKhterritory() {
        return this.khterritory;
    }

    public void setKhterritory(String khterritory) {
        this.khterritory = khterritory;
    }

    public String getFunds() {
        return this.funds;
    }

    public void setFunds(String funds) {
        this.funds = funds;
    }

    public String getStragegy() {
        return this.stragegy;
    }

    public void setStragegy(String stragegy) {
        this.stragegy = stragegy;
    }

    public String getCpr() {
        return this.cpr;
    }

    public void setCpr(String cpr) {
        this.cpr = cpr;
    }

    public Set<KingdomHall> getKingdomHalls() {
        return this.kingdomHalls;
    }

    public void setKingdomHalls(Set<KingdomHall> kingdomHalls) {
        this.kingdomHalls = kingdomHalls;
    }
}
