package uk.org.rbc1b.roms.db;
// Generated Apr 12, 2012 2:36:09 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * KingdomHall generated by hbm2java
 */
public class KingdomHall implements java.io.Serializable {

    private String kingdomHall;
    private Congregation congregation;
    private String street;
    private String town;
    private String county;
    private String postcode;
    private String maintenanceNotes;
    private String updateInfo;
    private String seating;
    private String parking;
    private String hallCondition;
    private String ownership;
    private Set congregations = new HashSet(0);
    private Set projects = new HashSet(0);

    public KingdomHall() {
    }

    public KingdomHall(String kingdomHall) {
        this.kingdomHall = kingdomHall;
    }

    public KingdomHall(String kingdomHall, Congregation congregation, String street, String town, String county, String postcode, String maintenanceNotes, String updateInfo, String seating, String parking, String hallCondition, String ownership, Set congregations, Set projects) {
        this.kingdomHall = kingdomHall;
        this.congregation = congregation;
        this.street = street;
        this.town = town;
        this.county = county;
        this.postcode = postcode;
        this.maintenanceNotes = maintenanceNotes;
        this.updateInfo = updateInfo;
        this.seating = seating;
        this.parking = parking;
        this.hallCondition = hallCondition;
        this.ownership = ownership;
        this.congregations = congregations;
        this.projects = projects;
    }

    public String getKingdomHall() {
        return this.kingdomHall;
    }

    public void setKingdomHall(String kingdomHall) {
        this.kingdomHall = kingdomHall;
    }

    public Congregation getCongregation() {
        return this.congregation;
    }

    public void setCongregation(Congregation congregation) {
        this.congregation = congregation;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getTown() {
        return this.town;
    }

    public void setTown(String town) {
        this.town = town;
    }

    public String getCounty() {
        return this.county;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getMaintenanceNotes() {
        return this.maintenanceNotes;
    }

    public void setMaintenanceNotes(String maintenanceNotes) {
        this.maintenanceNotes = maintenanceNotes;
    }

    public String getUpdateInfo() {
        return this.updateInfo;
    }

    public void setUpdateInfo(String updateInfo) {
        this.updateInfo = updateInfo;
    }

    public String getSeating() {
        return this.seating;
    }

    public void setSeating(String seating) {
        this.seating = seating;
    }

    public String getParking() {
        return this.parking;
    }

    public void setParking(String parking) {
        this.parking = parking;
    }

    public String getHallCondition() {
        return this.hallCondition;
    }

    public void setHallCondition(String hallCondition) {
        this.hallCondition = hallCondition;
    }

    public String getOwnership() {
        return this.ownership;
    }

    public void setOwnership(String ownership) {
        this.ownership = ownership;
    }

    public Set getCongregations() {
        return this.congregations;
    }

    public void setCongregations(Set congregations) {
        this.congregations = congregations;
    }

    public Set getProjects() {
        return this.projects;
    }

    public void setProjects(Set projects) {
        this.projects = projects;
    }
}
