package uk.org.rbc1b.roms.db;
// Generated Apr 12, 2012 2:36:09 PM by Hibernate Tools 3.2.1.GA

import java.util.Set;

/**
 * ProjectType generated by hbm2java
 */
public class ProjectType implements java.io.Serializable {

    private String projectType;
    private String description;
    private String updateInfo;
    private Set<Project> projects;

    public ProjectType() {
    }

    public ProjectType(String projectType) {
        this.projectType = projectType;
    }

    public ProjectType(String projectType, String description, String updateInfo, Set projects) {
        this.projectType = projectType;
        this.description = description;
        this.updateInfo = updateInfo;
        this.projects = projects;
    }

    public String getProjectType() {
        return this.projectType;
    }

    public void setProjectType(String projectType) {
        this.projectType = projectType;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUpdateInfo() {
        return this.updateInfo;
    }

    public void setUpdateInfo(String updateInfo) {
        this.updateInfo = updateInfo;
    }

    public Set<Project> getProjects() {
        return this.projects;
    }

    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }
}
