package uk.org.rbc1b.roms.db;
// Generated Apr 12, 2012 2:47:03 PM by Hibernate Tools 3.2.1.GA

/**
 * ProjectWorkStage generated by hbm2java.
 */
public class ProjectWorkStage implements java.io.Serializable {

    private ProjectWorkStageId id;
    private String assignedTo;
    private String workNotes;
    private String updateInfo;

    public ProjectWorkStageId getId() {
        return this.id;
    }

    public void setId(ProjectWorkStageId id) {
        this.id = id;
    }

    public String getAssignedTo() {
        return this.assignedTo;
    }

    public void setAssignedTo(String assignedTo) {
        this.assignedTo = assignedTo;
    }

    public String getWorkNotes() {
        return this.workNotes;
    }

    public void setWorkNotes(String workNotes) {
        this.workNotes = workNotes;
    }

    public String getUpdateInfo() {
        return this.updateInfo;
    }

    public void setUpdateInfo(String updateInfo) {
        this.updateInfo = updateInfo;
    }
}
